/*
 * Copyright (C) 2026 Thành Mai (thnhmai06)
 *
 * Solution: SlideGenerator
 * Project: SlideGenerator.Generator
 * File: Service.cs
 *
 * This file is part of this solution.
 * You can find the full source code here: https://github.com/thnhmai06/SlideGenerator.
 *
 * Licensed under the Apache License 2.0.
 * See the LICENSE file in the project root for full license information.
 */

using Microsoft.Data.Sqlite;
using Microsoft.Extensions.Logging;
using SlideGenerator.Document.Models.Slide;
using SlideGenerator.Generator.Application.Abstractions;
using SlideGenerator.Generator.Application.Workflows;
using SlideGenerator.Generator.Domain.Models.Data;
using SlideGenerator.Generator.Domain.Models.Enum;
using SlideGenerator.Recipe.Abstractions;
using SlideGenerator.Recipe.Models;
using SlideGenerator.Settings.Abstractions;
using SlideGenerator.Settings.Rules;
using SlideGenerator.Utilities;
using WorkflowCore.Interface;
using WorkflowCore.Models;
using WorkflowCore.Models.LifeCycleEvents;

namespace SlideGenerator.Generator.Infrastructure.Services;

/// <summary>
///     Implements <see cref="IService" /> by wrapping the WorkflowCore
///     <see cref="IWorkflowHost" /> and <see cref="IWorkflowController" />.
///     Lives in Infrastructure because it has a direct dependency on the WorkflowCore framework.
///     <c>StartAsync</c>'s spawn phase (reading the recipe, computing the job list, cleaning up nothing
///     shared) runs as plain code here — deliberately NOT a WorkflowCore workflow itself, so it is never
///     throttled by <c>WorkflowOptions.MaxConcurrentWorkflows</c> alongside the <see cref="JobWorkflow" />
///     instances it spawns.
/// </summary>
internal sealed class Service(
    IWorkflowHost workflowHost,
    IWorkflowController workflowController,
    IPersistenceProvider persistence,
    IEventBus eventBus,
    IRecipeRepository recipeRepository,
    IStudioRepository studioRepository,
    ILogFileReader logFileReader,
    WorkflowOptions workflowOptions,
    ISettingProvider settingProvider,
    ILogger<Service> logger)
    : IService
{
    private bool _isStarted;
    private LifeCycleEventHandler? _lifeCycleHandler;

    /// <inheritdoc />
    public async Task InitializeAsync(CancellationToken ct = default)
    {
        workflowHost.RegisterWorkflow<JobWorkflow, JobContext>();
        ApplyMaxConcurrentJobs();

        _lifeCycleHandler = HandleLifeCycleEvent;
        workflowHost.OnLifeCycleEvent += _lifeCycleHandler;

        await workflowHost.StartAsync(ct).ConfigureAwait(false);
        _isStarted = true;
        logger.LogInformation("WorkflowCore host started and JobWorkflow registered.");
    }

    /// <inheritdoc />
    public async Task ShutdownAsync(CancellationToken ct = default)
    {
        if (!_isStarted)
        {
            logger.LogDebug("WorkflowCore host was not started; skipping stop.");
            return;
        }

        if (_lifeCycleHandler is not null)
            workflowHost.OnLifeCycleEvent -= _lifeCycleHandler;

        await workflowHost.StopAsync(ct).ConfigureAwait(false);
        _isStarted = false;
        logger.LogInformation("WorkflowCore host stopped.");
    }

    /// <inheritdoc />
    public async Task<string> CreateAsync(Request request, CancellationToken ct = default)
    {
        using var scope = logger.BeginScope("Start/{RecipeId}/{RequestName}", request.RecipeId, request.Name);

        ApplyMaxConcurrentJobs();

        var entry = await recipeRepository.GetAsync(request.RecipeId, ct).ConfigureAwait(false)
                    ?? throw new InvalidOperationException($"Recipe {request.RecipeId} not found.");

        var requestId = Guid.NewGuid().ToString();
        var logPath = ResolveWorkflowLogPath(request);
        var jobs = BuildJobs(entry.Recipe, request);

        var conflictingPath = await FindConflictingOutputPathAsync(jobs).ConfigureAwait(false);
        if (conflictingPath is not null)
            throw new InvalidOperationException(
                $"Output path '{conflictingPath}' is already being generated by an active request.");

        eventBus.Publish(new RequestProgress
        {
            RequestId = requestId,
            Phase = RequestPhase.PreparationStarted,
            Timestamp = DateTimeOffset.UtcNow
        });
        eventBus.AnnounceExpectedJobCount(requestId, jobs.Count);

        foreach (var job in jobs)
        {
            var jobContext = new JobContext
            {
                Persist = new JobPersistContext
                {
                    RequestId = requestId,
                    Request = request,
                    Recipe = entry.Recipe,
                    LogPath = logPath,
                    Specification = job
                }
            };
            var jobId = await workflowHost.StartWorkflow(nameof(JobWorkflow), 1, jobContext).ConfigureAwait(false);
            eventBus.Publish(new JobProgress
            {
                RequestId = requestId,
                JobId = jobId,
                Status = Status.Pending,
                Timestamp = DateTimeOffset.UtcNow
            });
            logger.LogInformation("JobSpec spawned | JobId: {JobId} | OutputPath: {OutputPath}", jobId, job.OutputPath);
        }

        logger.LogInformation("Request started | RequestId: {RequestId} | Jobs: {Count}", requestId, jobs.Count);
        return requestId;
    }

    /// <inheritdoc />
    public async Task<PartialResult> StopAsync(string requestId, CancellationToken ct = default)
    {
        var jobs = await LoadGroupAsync(requestId).ConfigureAwait(false);
        return await FanOutAsync(requestId, jobs, WorkflowStatus.Runnable,
                workflowController.TerminateWorkflow, Status.Cancelled)
            .ConfigureAwait(false);
    }

    /// <inheritdoc />
    public async Task<PartialResult> PauseAsync(string requestId, CancellationToken ct = default)
    {
        var jobs = await LoadGroupAsync(requestId).ConfigureAwait(false);
        return await FanOutAsync(requestId, jobs, WorkflowStatus.Runnable,
                workflowController.SuspendWorkflow, Status.Paused)
            .ConfigureAwait(false);
    }

    /// <inheritdoc />
    public async Task<PartialResult> ResumeAsync(string requestId, CancellationToken ct = default)
    {
        var jobs = await LoadGroupAsync(requestId).ConfigureAwait(false);
        return await FanOutAsync(requestId, jobs, WorkflowStatus.Suspended,
                workflowController.ResumeWorkflow, Status.Running)
            .ConfigureAwait(false);
    }

    /// <inheritdoc />
    public async Task<int> StopAllAsync(CancellationToken ct = default)
    {
        var actives = await ListActiveAsync(ct).ConfigureAwait(false);
        var count = 0;
        foreach (var requestId in actives.Keys)
        {
            var result = await StopAsync(requestId, ct).ConfigureAwait(false);
            if (result.Succeeded > 0) count++;
        }

        return count;
    }

    /// <inheritdoc />
    public async Task<int> PauseAllAsync(CancellationToken ct = default)
    {
        var actives = await ListActiveAsync(ct).ConfigureAwait(false);
        var count = 0;
        foreach (var requestId in actives.Where(kv => kv.Value.Status == Status.Running).Select(kv => kv.Key))
        {
            var result = await PauseAsync(requestId, ct).ConfigureAwait(false);
            if (result.Succeeded > 0) count++;
        }

        return count;
    }

    /// <summary>
    ///     Re-applies <c>Performance.MaxConcurrentJobs</c> from the current settings onto the running
    ///     WorkflowCore host's <c>MaxConcurrentWorkflows</c>. Called once at startup and opportunistically
    ///     at the start of every <see cref="CreateAsync" /> — <see cref="Service" /> reads
    ///     <see cref="ISettingProvider" /> itself rather than being told to re-apply externally.
    /// </summary>
    private void ApplyMaxConcurrentJobs()
    {
        var value = (int)settingProvider.Current.Performance.MaxConcurrentJobs;
        workflowOptions.UseMaxConcurrentWorkflows(value);
        logger.LogInformation("MaxConcurrentWorkflows set to {Value}.", value);
    }

    /// <inheritdoc />
    public async Task<IReadOnlyDictionary<string, Summary>> ListActiveAsync(CancellationToken ct = default)
    {
        var groups = await ListGroupsAsync().ConfigureAwait(false);
        var active = groups.Where(kv => DeriveStatus(kv.Value) is Status.Running or Status.Paused);
        return await ToSummariesAsync(active, ct).ConfigureAwait(false);
    }

    /// <inheritdoc />
    public async Task<IReadOnlyDictionary<string, Summary>> ListCompletedAsync(CancellationToken ct = default)
    {
        var groups = await ListGroupsAsync().ConfigureAwait(false);
        var completed = groups.Where(kv => DeriveStatus(kv.Value) is Status.Complete or Status.Cancelled);
        return await ToSummariesAsync(completed, ct).ConfigureAwait(false);
    }

    private async Task<IReadOnlyDictionary<string, Summary>> ToSummariesAsync(
        IEnumerable<KeyValuePair<string, IReadOnlyList<WorkflowInstance>>> groups, CancellationToken ct)
    {
        var result = new Dictionary<string, Summary>();
        foreach (var (requestId, jobs) in groups)
            result[requestId] = await ToSummaryAsync(requestId, jobs, ct).ConfigureAwait(false);
        return result;
    }

    /// <summary>
    ///     Returns the first output path among <paramref name="jobs" /> that collides with an output path
    ///     already claimed by a job of another active (running or paused) request — or
    ///     <see langword="null" /> if none collide. Same-recipe requests are otherwise allowed to run
    ///     concurrently; only an actual output-file clash is rejected.
    /// </summary>
    private async Task<string?> FindConflictingOutputPathAsync(IReadOnlyList<JobSpecification> jobs)
    {
        var groups = await ListGroupsAsync().ConfigureAwait(false);
        var activeOutputPaths = groups
            .Where(kv => DeriveStatus(kv.Value) is Status.Running or Status.Paused)
            .SelectMany(kv => kv.Value)
            .Select(wi => (wi.Data as JobContext)?.Persist.Specification.OutputPath)
            .Where(path => path is not null)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        return jobs.Select(j => j.OutputPath).FirstOrDefault(activeOutputPaths.Contains);
    }

    /// <inheritdoc />
    public async Task<bool> DeleteAsync(string requestId, CancellationToken ct = default)
    {
        var jobs = await LoadGroupAsync(requestId).ConfigureAwait(false);
        if (jobs is null)
        {
            logger.LogWarning("Request {RequestId} not found — delete skipped.", requestId);
            return false;
        }

        if (DeriveStatus(jobs) is Status.Running or Status.Paused)
            await StopAsync(requestId, ct).ConfigureAwait(false);

        await studioRepository.DeleteRequestAsync(requestId, ct).ConfigureAwait(false);

        await using var conn = new SqliteConnection(NameAndPaths.DataFolder.WorkflowsFile.ConnectionString);
        await conn.OpenAsync(ct).ConfigureAwait(false);
        await using var tx = conn.BeginTransaction();
        try
        {
            var deleted = 0;
            foreach (var job in jobs)
                deleted += await DeleteInstanceAsync(conn, tx, job.Id, ct).ConfigureAwait(false);

            tx.Commit();
            logger.LogInformation("Deleted request {RequestId} ({Count} job(s)).", requestId, deleted);
            return deleted > 0;
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to delete request | Reason: DB transaction error | RequestId: {RequestId}",
                requestId);
            tx.Rollback();
            throw;
        }
    }

    /// <inheritdoc />
    public async Task<int> DeleteAllCompletedAsync(CancellationToken ct = default)
    {
        var completed = await ListCompletedAsync(ct).ConfigureAwait(false);

        await using var conn = new SqliteConnection(NameAndPaths.DataFolder.WorkflowsFile.ConnectionString);
        await conn.OpenAsync(ct).ConfigureAwait(false);
        await using var tx = conn.BeginTransaction();
        try
        {
            var deletedRequests = 0;
            foreach (var requestId in completed.Keys)
            {
                var jobs = await LoadGroupAsync(requestId).ConfigureAwait(false);
                if (jobs is null) continue;
                foreach (var job in jobs)
                    await DeleteInstanceAsync(conn, tx, job.Id, ct).ConfigureAwait(false);
                await studioRepository.DeleteRequestAsync(requestId, ct).ConfigureAwait(false);
                deletedRequests++;
            }

            tx.Commit();
            logger.LogInformation("Deleted {Count} completed/cancelled request(s).", deletedRequests);
            return deletedRequests;
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to delete completed requests | Reason: DB transaction error");
            tx.Rollback();
            throw;
        }
    }

    #region Aggregation helpers

    private async Task<IReadOnlyDictionary<string, IReadOnlyList<WorkflowInstance>>> ListGroupsAsync()
    {
        // WorkflowCore 3.18.0 has no non-obsolete way to list every instance of a given workflow type:
        // GetWorkflowInstance(id) needs a known id, GetWorkflowInstances(ids) needs a known id set,
        // GetRunnableInstances only returns runnable ones, and ISearchIndex is a separate opt-in
        // full-text search provider (not registered here) — not a fit for this simple type+status query.
#pragma warning disable CS0612
        var all = await persistence
            .GetWorkflowInstances(null, nameof(JobWorkflow), null, null, 0, int.MaxValue)
            .ConfigureAwait(false);
#pragma warning restore CS0612
        return all
            .Where(wi => wi.Data is JobContext)
            .GroupBy(wi => ((JobContext)wi.Data).Persist.RequestId)
            .ToDictionary(g => g.Key, IReadOnlyList<WorkflowInstance> (g) => g.ToList());
    }

    private async Task<IReadOnlyList<WorkflowInstance>?> LoadGroupAsync(string requestId)
    {
        var groups = await ListGroupsAsync().ConfigureAwait(false);
        return groups.GetValueOrDefault(requestId);
    }

    private async Task<PartialResult> FanOutAsync(
        string requestId, IReadOnlyList<WorkflowInstance>? jobs, WorkflowStatus eligibleStatus,
        Func<string, Task<bool>> action, Status status)
    {
        if (jobs is null) return new PartialResult(0, 0);

        var succeeded = 0;
        var skipped = 0;
        foreach (var job in jobs)
        {
            if (job.Status != eligibleStatus)
            {
                skipped++;
                continue;
            }

            var ok = await action(job.Id).ConfigureAwait(false);
            if (ok)
            {
                succeeded++;
                eventBus.Publish(new JobProgress
                {
                    RequestId = requestId,
                    JobId = job.Id,
                    Status = status,
                    Timestamp = DateTimeOffset.UtcNow
                });
            }
            else
            {
                skipped++;
            }
        }

        return new PartialResult(succeeded, skipped);
    }

    internal static List<JobSpecification> BuildJobs(Recipe.Models.Recipe recipe, Request request)
    {
        var jobs = new List<JobSpecification>();
        var mapNodes = recipe.Nodes
            .Where(kvp => kvp.Value is MapNode)
            .Select(kvp => (kvp.Key, (MapNode)kvp.Value));
        foreach (var (mapId, _) in mapNodes)
        {
            var incomingIds = recipe.Edges
                .Where(e => e.ToId == mapId)
                .Select(e => e.FromId)
                .ToHashSet();

            var slideNodeId = recipe.Edges
                .Where(e => e.FromId == mapId)
                .Select(e => e.ToId)
                .FirstOrDefault(id => recipe.Nodes.ContainsKey(id) && recipe.Nodes[id] is SlideNode);

            var presentationEntry = slideNodeId != null
                ? recipe.Nodes.FirstOrDefault(kvp =>
                    kvp.Value is PresentationNode pn && pn.SlideIds.Contains(slideNodeId))
                : default;

            if (slideNodeId == null || presentationEntry.Key == null) continue;

            foreach (var (workbookNodeId, workbookNode) in recipe.Nodes
                         .Where(kvp => kvp.Value is WorkbookNode)
                         .Select(kvp => (kvp.Key, (WorkbookNode)kvp.Value)))
            {
                foreach (var wsId in workbookNode.WorksheetIds.Where(incomingIds.Contains))
                {
                    if (recipe.Nodes[wsId] is not WorksheetNode worksheetNode) continue;

                    var bookName = Path.GetFileNameWithoutExtension(workbookNode.Workbook.BookPath);
                    var outputFileName =
                        $"{Naming.SanitizeFileName(worksheetNode.Worksheet.SheetName)}{request.OutputType.ToExtension()}";
                    var outputPath = Path.Combine(request.SaveFolder, bookName, outputFileName);

                    jobs.Add(new JobSpecification
                    {
                        Source = new WorkbookRef(workbookNodeId, wsId),
                        Template = new PresentationRef(presentationEntry.Key, slideNodeId),
                        MapNodeId = mapId,
                        OutputPath = outputPath
                    });
                }
            }
        }

        return jobs;
    }

    #endregion

    /// <summary>
    ///     Handles a WorkflowCore lifecycle event for a single job instance. <c>async void</c> is
    ///     deliberate here — <see cref="IWorkflowHost.OnLifeCycleEvent" /> is a synchronous event, and
    ///     resolving <see cref="JobPersistContext.RequestId" /> for the job needs an async persistence
    ///     lookup. Exceptions are caught locally, so a lookup failure can't crash the process.
    /// </summary>
    // ReSharper disable once AsyncVoidMethod
    private async void HandleLifeCycleEvent(LifeCycleEvent e)
    {
        string jobId;
        Status status;
        switch (e)
        {
            case WorkflowStarted ws:
                jobId = ws.WorkflowInstanceId;
                status = Status.Running;
                break;
            case WorkflowCompleted wc:
                jobId = wc.WorkflowInstanceId;
                status = Status.Complete;
                break;
            case WorkflowError we:
                jobId = we.WorkflowInstanceId;
                status = Status.Error;
                break;
            default:
                return;
        }

        var requestId = jobId;
        try
        {
            var instance = await persistence.GetWorkflowInstance(jobId, CancellationToken.None).ConfigureAwait(false);
            if (instance?.Data is JobContext jobContext) requestId = jobContext.Persist.RequestId;
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Failed to resolve RequestId for job {JobId} lifecycle event.", jobId);
        }

        eventBus.Publish(new JobProgress
        {
            RequestId = requestId,
            JobId = jobId,
            Status = status,
            Timestamp = DateTimeOffset.UtcNow
        });
    }

    /// <summary>
    ///     Deletes a single completed/terminated <c>Workflow</c> row and its dependents. Column/join shape
    ///     matches WorkflowCore's actual SQLite schema (verified against a live <c>Workflows.db</c>):
    ///     <c>Workflow.InstanceId</c> (TEXT, the GUID job id) — not <c>Id</c>, which doesn't exist on this
    ///     table; <c>ExecutionPointer.WorkflowId</c>/<c>ExtensionAttribute.ExecutionPointerId</c> are
    ///     INTEGER FKs to the referenced row's <c>PersistenceId</c> — not the GUID/TEXT id; only
    ///     <c>ExecutionError.WorkflowId</c> is a loose TEXT column holding the GUID directly (no FK
    ///     declared on it at all), so it needs no join.
    /// </summary>
    private static async Task<int> DeleteInstanceAsync(
        SqliteConnection conn, SqliteTransaction tx, string instanceId, CancellationToken ct)
    {
        await DeleteExtensionAttributesAsync(conn, tx, instanceId, ct).ConfigureAwait(false);
        await DeleteExecutionErrorsAsync(conn, tx, instanceId, ct).ConfigureAwait(false);
        await DeleteExecutionPointersAsync(conn, tx, instanceId, ct).ConfigureAwait(false);

        await using var cmd = conn.CreateCommand();
        cmd.Transaction = tx;
        cmd.CommandText =
            $"DELETE FROM \"Workflow\" WHERE \"InstanceId\" = @id AND \"Status\" IN ({(int)WorkflowStatus.Complete}, {(int)WorkflowStatus.Terminated})";
        cmd.Parameters.AddWithValue("@id", instanceId);
        return await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
    }

    private static async Task DeleteExtensionAttributesAsync(
        SqliteConnection conn, SqliteTransaction tx, string instanceId, CancellationToken ct)
    {
        await using var cmd = conn.CreateCommand();
        cmd.Transaction = tx;
        cmd.CommandText =
            "DELETE FROM \"ExtensionAttribute\" WHERE \"ExecutionPointerId\" IN (" +
            "SELECT ep.\"PersistenceId\" FROM \"ExecutionPointer\" ep " +
            "INNER JOIN \"Workflow\" w ON w.\"PersistenceId\" = ep.\"WorkflowId\" " +
            "WHERE w.\"InstanceId\" = @id)";
        cmd.Parameters.AddWithValue("@id", instanceId);
        await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
    }

    private static async Task DeleteExecutionErrorsAsync(
        SqliteConnection conn, SqliteTransaction tx, string instanceId, CancellationToken ct)
    {
        await using var cmd = conn.CreateCommand();
        cmd.Transaction = tx;
        cmd.CommandText = "DELETE FROM \"ExecutionError\" WHERE \"WorkflowId\" = @id";
        cmd.Parameters.AddWithValue("@id", instanceId);
        await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
    }

    private static async Task DeleteExecutionPointersAsync(
        SqliteConnection conn, SqliteTransaction tx, string instanceId, CancellationToken ct)
    {
        await using var cmd = conn.CreateCommand();
        cmd.Transaction = tx;
        cmd.CommandText =
            "DELETE FROM \"ExecutionPointer\" WHERE \"WorkflowId\" IN (" +
            "SELECT \"PersistenceId\" FROM \"Workflow\" WHERE \"InstanceId\" = @id)";
        cmd.Parameters.AddWithValue("@id", instanceId);
        await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
    }

    private async Task<Summary> ToSummaryAsync(
        string requestId, IReadOnlyList<WorkflowInstance> jobs, CancellationToken ct)
    {
        var status = DeriveStatus(jobs);
        // ListGroupsAsync only ever produces groups from instances whose Data is JobContext, so this cast
        // is guaranteed to succeed for every job in the group.
        var first = (JobContext)jobs[0].Data;
        var createdAt = jobs.Min(j => j.CreateTime);
        var completedAt = status is Status.Complete or Status.Cancelled
            ? jobs.Max(j => j.CompleteTime ?? j.CreateTime)
            : (DateTime?)null;

        var requestProgress = await studioRepository.GetRequestAsync(requestId, ct).ConfigureAwait(false);
        var jobProgress = await studioRepository.GetJobsAsync(requestId, ct).ConfigureAwait(false);
        var logEntries = logFileReader.ReadAll(first.Persist.LogPath);

        var jobSummaries = new Dictionary<string, JobSummary>();
        foreach (var job in jobs)
            jobSummaries[job.Id] = await ToJobSummaryAsync(requestId, job, jobProgress, logEntries, ct)
                .ConfigureAwait(false);

        return new Summary
        {
            Request = first.Persist.Request,
            Status = status,
            Phase = requestProgress?.Phase,
            CreatedAt = new DateTimeOffset(createdAt, TimeSpan.Zero),
            CompletedAt = completedAt.HasValue ? new DateTimeOffset(completedAt.Value, TimeSpan.Zero) : null,
            Logs = logEntries.Where(e => e.Path == requestId).ToList(),
            Jobs = jobSummaries
        };
    }

    private async Task<JobSummary> ToJobSummaryAsync(
        string requestId, WorkflowInstance job, IReadOnlyDictionary<string, JobProgress> jobProgress,
        IReadOnlyList<LogEntry> logEntries, CancellationToken ct)
    {
        var outputPath = (job.Data as JobContext)?.Persist.Specification.OutputPath ?? string.Empty;
        var status = jobProgress.TryGetValue(job.Id, out var jp) ? jp.Status : ToJobStatus(job.Status);
        var jobScopePrefix = $"{requestId}/{job.Id}";

        var rowProgress = await studioRepository.GetRowsAsync(requestId, job.Id, ct).ConfigureAwait(false);
        var rowSummaries = rowProgress.ToDictionary(kv => kv.Key, kv => new RowSummary
        {
            Status = kv.Value.Status,
            Stage = kv.Value.Stage,
            Note = kv.Value.Note,
            Timestamp = kv.Value.Timestamp,
            Logs = logEntries.Where(e => e.Path == $"{jobScopePrefix}/{kv.Key}").ToList()
        });

        return new JobSummary
        {
            Status = status,
            OutputPath = outputPath,
            CompletedAt = job.CompleteTime.HasValue
                ? new DateTimeOffset(job.CompleteTime.Value, TimeSpan.Zero)
                : null,
            Rows = rowSummaries,
            Logs = logEntries
                .Where(e => e.Path == jobScopePrefix || e.Path.StartsWith(jobScopePrefix + "/", StringComparison.Ordinal))
                .ToList()
        };
    }

    private static Status ToJobStatus(WorkflowStatus status) => status switch
    {
        WorkflowStatus.Runnable => Status.Running,
        WorkflowStatus.Suspended => Status.Paused,
        WorkflowStatus.Terminated => Status.Cancelled,
        _ => Status.Complete
    };

    internal static Status DeriveStatus(IReadOnlyList<WorkflowInstance> jobs)
    {
        if (jobs.Any(j => j.Status == WorkflowStatus.Runnable)) return Status.Running;
        if (jobs.Any(j => j.Status == WorkflowStatus.Suspended)) return Status.Paused;
        if (jobs.All(j => j.Status == WorkflowStatus.Terminated)) return Status.Cancelled;
        return Status.Complete;
    }

    private static string ResolveWorkflowLogPath(Request request)
    {
        var fileName = Naming.SanitizeFileName(request.Name);
        if (string.IsNullOrWhiteSpace(fileName)) fileName = "workflow";
        return Path.Combine(NameAndPaths.LogsFolder.WorkflowPath, $"{fileName}.log");
    }
}