# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\error.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_error_notice(object):
    def setupUi(self, error_notice):
        error_notice.setObjectName("error_notice")
        error_notice.resize(427, 144)
        error_notice.setMinimumSize(QtCore.QSize(427, 144))
        error_notice.setMaximumSize(QtCore.QSize(427, 144))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/notice/error"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        error_notice.setWindowIcon(icon)
        self.image = QtWidgets.QLabel(error_notice)
        self.image.setGeometry(QtCore.QRect(20, 20, 51, 51))
        self.image.setObjectName("image")
        self.okbutton = QtWidgets.QPushButton(error_notice)
        self.okbutton.setGeometry(QtCore.QRect(170, 90, 91, 31))
        self.okbutton.setObjectName("okbutton")
        self.label = QtWidgets.QLabel(error_notice)
        self.label.setGeometry(QtCore.QRect(100, 30, 301, 31))
        self.label.setObjectName("label")

        self.retranslateUi(error_notice)
        QtCore.QMetaObject.connectSlotsByName(error_notice)

    def retranslateUi(self, error_notice):
        _translate = QtCore.QCoreApplication.translate
        error_notice.setWindowTitle(_translate("error_notice", "Lỗi"))
        self.image.setText(_translate("error_notice", "<html><head/><body><p><img src=\":/notice/error\"/></p></body></html>"))
        self.okbutton.setText(_translate("error_notice", "OK"))
        self.label.setText(_translate("error_notice", "<html><head/><body><p><span style=\" font-size:12pt;\">Đã có lỗi xảy ra, vui lòng kiểm tra Console</span></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    error_notice = QtWidgets.QDialog()
    ui = Ui_error_notice()
    ui.setupUi(error_notice)
    error_notice.show()
    sys.exit(app.exec_())
