# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\error.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_error(object):
    def setupUi(self, error):
        error.setObjectName("error")
        error.resize(571, 324)
        error.setMinimumSize(QtCore.QSize(571, 324))
        error.setMaximumSize(QtCore.QSize(571, 324))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/notice/error"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        error.setWindowIcon(icon)
        self.image = QtWidgets.QLabel(error)
        self.image.setGeometry(QtCore.QRect(20, 20, 51, 51))
        self.image.setObjectName("image")
        self.okbutton = QtWidgets.QPushButton(error)
        self.okbutton.setGeometry(QtCore.QRect(250, 280, 91, 31))
        self.okbutton.setObjectName("okbutton")
        self.label = QtWidgets.QLabel(error)
        self.label.setGeometry(QtCore.QRect(80, 30, 141, 31))
        self.label.setObjectName("label")
        self.details = QtWidgets.QTextEdit(error)
        self.details.setGeometry(QtCore.QRect(80, 70, 461, 191))
        self.details.setObjectName("details")

        self.retranslateUi(error)
        QtCore.QMetaObject.connectSlotsByName(error)


    def retranslateUi(self, error):
        _translate = QtCore.QCoreApplication.translate
        error.setWindowTitle(_translate("error", "Lỗi"))
        self.image.setText(_translate("error", "<html><head/><body><p><img src=\":/notice/error\"/></p></body></html>"))
        self.okbutton.setText(_translate("error", "OK"))
        self.label.setText(_translate("error", "<html><head/><body><p><span style=\" font-size:14pt;\">Đã có lỗi xảy ra:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    error = QtWidgets.QDialog()
    ui = Ui_error()
    ui.setupUi(error)
    error.show()
    sys.exit(app.exec_())
