# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\information.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_information(object):
    def setupUi(self, information):
        information.setObjectName("information")
        information.resize(427, 144)
        information.setMinimumSize(QtCore.QSize(427, 144))
        information.setMaximumSize(QtCore.QSize(427, 144))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/notice/information"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        information.setWindowIcon(icon)
        self.image = QtWidgets.QLabel(information)
        self.image.setGeometry(QtCore.QRect(20, 20, 51, 51))
        self.image.setObjectName("image")
        self.okbutton = QtWidgets.QPushButton(information)
        self.okbutton.setGeometry(QtCore.QRect(170, 100, 91, 31))
        self.okbutton.setObjectName("okbutton")
        self.label = QtWidgets.QLabel(information)
        self.label.setGeometry(QtCore.QRect(100, 20, 301, 51))
        self.label.setObjectName("label")

        self.retranslateUi(information)
        QtCore.QMetaObject.connectSlotsByName(information)

    def retranslateUi(self, information):
        _translate = QtCore.QCoreApplication.translate
        information.setWindowTitle(_translate("information", "Thông báo"))
        self.image.setText(_translate("information", "<html><head/><body><p><img src=\":/notice/information\"/></p></body></html>"))
        self.okbutton.setText(_translate("information", "OK"))
        self.label.setText(_translate("information", "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    information = QtWidgets.QDialog()
    ui = Ui_information()
    ui.setupUi(information)
    information.show()
    sys.exit(app.exec_())
