# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\information.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_information_notice(object):
    def setupUi(self, information_notice):
        information_notice.setObjectName("information_notice")
        information_notice.resize(427, 144)
        information_notice.setMinimumSize(QtCore.QSize(427, 144))
        information_notice.setMaximumSize(QtCore.QSize(427, 144))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/notice/information"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        information_notice.setWindowIcon(icon)
        self.image = QtWidgets.QLabel(information_notice)
        self.image.setGeometry(QtCore.QRect(20, 20, 51, 51))
        self.image.setObjectName("image")
        self.okbutton = QtWidgets.QPushButton(information_notice)
        self.okbutton.setGeometry(QtCore.QRect(170, 90, 91, 31))
        self.okbutton.setObjectName("okbutton")
        self.label = QtWidgets.QLabel(information_notice)
        self.label.setGeometry(QtCore.QRect(100, 20, 301, 51))
        self.label.setObjectName("label")

        self.retranslateUi(information_notice)
        QtCore.QMetaObject.connectSlotsByName(information_notice)

    def retranslateUi(self, information_notice):
        _translate = QtCore.QCoreApplication.translate
        information_notice.setWindowTitle(_translate("information_notice", "Thông báo"))
        self.image.setText(_translate("information_notice", "<html><head/><body><p><img src=\":/notice/information\"/></p></body></html>"))
        self.okbutton.setText(_translate("information_notice", "OK"))
        self.label.setText(_translate("information_notice", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Vui lòng cài đặt Microsoft PowerPoint (Office) <br/>để sử dụng phần mềm này!</span><br/></p></body></html>"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    information_notice = QtWidgets.QDialog()
    ui = Ui_information_notice()
    ui.setupUi(information_notice)
    information_notice.show()
    sys.exit(app.exec_())
