# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_progress(object):
    def setupUi(self, progress):
        progress.setObjectName("progress")
        progress.resize(574, 374)
        self.progressBar = QtWidgets.QProgressBar(progress)
        self.progressBar.setGeometry(QtCore.QRect(20, 50, 541, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.stop_button = QtWidgets.QPushButton(progress)
        self.stop_button.setGeometry(QtCore.QRect(450, 320, 101, 41))
        self.stop_button.setObjectName("stop_button")
        self.pause_button = QtWidgets.QPushButton(progress)
        self.pause_button.setGeometry(QtCore.QRect(330, 320, 101, 41))
        self.pause_button.setObjectName("pause_button")
        self.label = QtWidgets.QLabel(progress)
        self.label.setGeometry(QtCore.QRect(20, 20, 141, 16))
        self.label.setObjectName("label")
        self.log = QtWidgets.QTextEdit(progress)
        self.log.setGeometry(QtCore.QRect(20, 100, 531, 211))
        self.log.setObjectName("log")

        self.retranslateUi(progress)
        QtCore.QMetaObject.connectSlotsByName(progress)

    def retranslateUi(self, progress):
        _translate = QtCore.QCoreApplication.translate
        progress.setWindowTitle(_translate("progress", "Dialog"))
        self.stop_button.setText(_translate("progress", "Dừng"))
        self.pause_button.setText(_translate("progress", "Tạm dừng"))
        self.label.setText(_translate("progress", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Đang tạo các slide...</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    progress = QtWidgets.QDialog()
    ui = Ui_progress()
    ui.setupUi(progress)
    progress.show()
    sys.exit(app.exec_())
