# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ui(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.retranslateUi()

    def setupUi(self):
        """
        Set up the user interface.
        """
        self.setObjectName("progress")
        self.resize(574, 374)

        self.initProgressBar()
        self.initButtons()
        self.initLabel()
        self.initLog()

        QtCore.QMetaObject.connectSlotsByName(self)

    def initProgressBar(self):
        """
        Initialize the progress bar.
        """
        self.progressBar = QtWidgets.QProgressBar(self)
        self.progressBar.setGeometry(QtCore.QRect(20, 50, 541, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")

    def initButtons(self):
        """
        Initialize the stop and pause buttons.
        """
        self.stop_button = QtWidgets.QPushButton(self)
        self.stop_button.setGeometry(QtCore.QRect(450, 320, 101, 41))
        self.stop_button.setObjectName("stop_button")

        self.pause_button = QtWidgets.QPushButton(self)
        self.pause_button.setGeometry(QtCore.QRect(330, 320, 101, 41))
        self.pause_button.setObjectName("pause_button")

    def initLabel(self):
        """
        Initialize the label.
        """
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(20, 20, 141, 16))
        self.label.setObjectName("label")

    def initLog(self):
        """
        Initialize the log text edit.
        """
        self.log = QtWidgets.QTextEdit(self)
        self.log.setGeometry(QtCore.QRect(20, 100, 531, 211))
        self.log.setObjectName("log")

    def retranslateUi(self):
        """
        Set the text for the UI elements.
        """
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("progress", "Tiến trình"))
        self.stop_button.setText(_translate("progress", "Dừng"))
        self.pause_button.setText(_translate("progress", "Tạm dừng"))
        self.label.setText(_translate("progress", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Đang tạo các slide...</span></p></body></html>"))
