<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Remove="StyleCop.Analyzers"/>
        <PackageReference Include="Avalonia.Headless.XUnit" Version="12.1.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="xunit.v3" Version="4.0.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NSubstitute" Version="6.2.0"/>
        <PackageReference Include="FluentAssertions" Version="8.10.0"/>
        <PackageReference Remove="coverlet.collector"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../../src/SlideGenerator.Desktop/SlideGenerator.Desktop.csproj"/>
    </ItemGroup>
</Project>
