# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import *
from handle import config_images, config_text, menu_broswe_button
from handle.menu_start_button import check_start_button
from src import load_csv, load_pptx, processing
from ui import progress
from globals import GITHUB_URL
from translation import TRANS

class Ui(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.retranslateUi()
        self.handleUI()
        self.progress = None  # Create a space for progress window and it will save here

    def setupUi(self):
        """
        Sets up the user interface for the menu window.
        This method initializes and configures the main window and its widgets.
        """
        self.setObjectName("menu")
        self.resize(959, 867)
        self.setMinimumSize(QtCore.QSize(959, 867))
        self.setMaximumSize(QtCore.QSize(959, 867))
        self.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.setMouseTracking(False)
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/uet"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.setWhatsThis("")
        self.setAutoFillBackground(False)
        
        self.centralwidget = QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        
        self.setupTitle()
        self.setupTemplateGroupBox()
        self.setupDSSVGroupBox()
        self.setupsaveGroupBox()
        self.setupConfigGroupBox()
        self.setupStartButton()
        self.setupLabels()
        
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        
        QtCore.QMetaObject.connectSlotsByName(self)

    def setupTitle(self):
        """Sets up the title label."""
        self.title = QLabel(self.centralwidget)
        self.title.setEnabled(True)
        self.title.setGeometry(QtCore.QRect(190, 20, 611, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setMouseTracking(False)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setScaledContents(False)
        self.title.setWordWrap(False)
        self.title.setObjectName("title")

    def setupTemplateGroupBox(self):
        """Sets up the template group box."""
        self.template = QGroupBox(self.centralwidget)
        self.template.setGeometry(QtCore.QRect(20, 120, 411, 161))
        self.template.setObjectName("template")
        
        self.template_broswe = QPushButton(self.template)
        self.template_broswe.setGeometry(QtCore.QRect(300, 90, 93, 28))
        self.template_broswe.setObjectName("template_broswe")
        
        self.pptx_path = QLineEdit(self.template)
        self.pptx_path.setGeometry(QtCore.QRect(20, 90, 271, 31))
        self.pptx_path.setCursorPosition(0)
        self.pptx_path.setDragEnabled(False)
        self.pptx_path.setObjectName("pptx_path")
        self.pptx_path.setReadOnly(True)
        self.pptx_path.setStyleSheet("background-color: #f0f0f0")
        
        self.template_label = QLabel(self.template)
        self.template_label.setGeometry(QtCore.QRect(20, 40, 171, 31))
        self.template_label.setObjectName("template_label")

    def setupDSSVGroupBox(self):
        """Sets up the DSSV group box."""
        self.dssv = QGroupBox(self.centralwidget)
        self.dssv.setGeometry(QtCore.QRect(510, 120, 411, 161))
        self.dssv.setObjectName("dssv")
        
        self.dssv_broswe = QPushButton(self.dssv)
        self.dssv_broswe.setGeometry(QtCore.QRect(300, 90, 93, 28))
        self.dssv_broswe.setObjectName("dssv_broswe")
        
        self.csv_path = QLineEdit(self.dssv)
        self.csv_path.setGeometry(QtCore.QRect(20, 90, 271, 31))
        self.csv_path.setCursorPosition(0)
        self.csv_path.setDragEnabled(False)
        self.csv_path.setObjectName("csv_path")
        self.csv_path.setReadOnly(True)
        self.csv_path.setStyleSheet("background-color: #f0f0f0")
        
        self.dssv_label = QLabel(self.dssv)
        self.dssv_label.setGeometry(QtCore.QRect(20, 40, 221, 31))
        self.dssv_label.setObjectName("dssv_label")

    def setupsaveGroupBox(self):
        """Sets up the save group box."""
        self.save = QGroupBox(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(20, 720, 411, 121))
        self.save.setObjectName("save")
        
        self.save_broswe = QPushButton(self.save)
        self.save_broswe.setGeometry(QtCore.QRect(300, 60, 93, 28))
        self.save_broswe.setObjectName("save_broswe")
        
        self.save_path = QLineEdit(self.save)
        self.save_path.setGeometry(QtCore.QRect(20, 60, 271, 31))
        self.save_path.setCursorPosition(0)
        self.save_path.setDragEnabled(False)
        self.save_path.setObjectName("save_path")
        self.save_path.setReadOnly(True)
        self.save_path.setStyleSheet("background-color: #f0f0f0")
        
        self.save_label = QLabel(self.save)
        self.save_label.setGeometry(QtCore.QRect(20, 20, 81, 31))
        self.save_label.setObjectName("save_label")

    def setupConfigGroupBox(self):
        """Sets up the config group box."""
        self.config = QGroupBox(self.centralwidget)
        self.config.setGeometry(QtCore.QRect(20, 300, 901, 401))
        self.config.setObjectName("config")
        
        self.config_text_list = QListWidget(self.config)
        self.config_text_list.setGeometry(QtCore.QRect(20, 60, 401, 301))
        self.config_text_list.setObjectName("config_text_list")
        self.config_text_list.setEnabled(False)

        self.config_image_table = QTableWidget(self.config)
        self.config_image_table.setGeometry(QtCore.QRect(470, 60, 401, 301))
        self.config_image_table.setObjectName("config_image_table")
        self.config_image_table.setColumnCount(2)
        self.config_image_table.setRowCount(0)
        self.config_image_table.setEnabled(False)
        
        item = QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.config_image_table.setHorizontalHeaderItem(0, item)
        
        item = QTableWidgetItem()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.config_image_table.setHorizontalHeaderItem(1, item)
        
        self.config_image_table.horizontalHeader().setHighlightSections(True)
        self.config_image_table.horizontalHeader().setSortIndicatorShown(False)
        self.config_image_table.horizontalHeader().setStretchLastSection(True)
        self.config_image_table.verticalHeader().setVisible(True)
        self.config_image_table.verticalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)
        self.config_image_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)
        
        self.config_text_label = QLabel(self.config)
        self.config_text_label.setGeometry(QtCore.QRect(20, 30, 401, 20))
        self.config_text_label.setObjectName("config_text_label")
        
        self.config_image_label = QLabel(self.config)
        self.config_image_label.setGeometry(QtCore.QRect(470, 30, 401, 20))
        self.config_image_label.setObjectName("config_image_label")
        
        self.config_image_autodownload_label = QLabel(self.config)
        self.config_image_autodownload_label.setGeometry(QtCore.QRect(470, 370, 211, 16))
        self.config_image_autodownload_label.setObjectName("config_image_autodownload_label")
        
        self.config_image_add_button = QPushButton(self.config)
        self.config_image_add_button.setGeometry(QtCore.QRect(800, 370, 31, 21))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/add"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.config_image_add_button.setIcon(icon1)
        self.config_image_add_button.setObjectName("config_image_add_button")
        self.config_image_add_button.setEnabled(False)
        
        self.config_image_remove_button = QPushButton(self.config)
        self.config_image_remove_button.setGeometry(QtCore.QRect(840, 370, 31, 21))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main/remove"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.config_image_remove_button.setIcon(icon2)
        self.config_image_remove_button.setObjectName("config_image_remove_button")
        self.config_image_remove_button.setEnabled(False)
        
        self.config_text_remove_button = QPushButton(self.config)
        self.config_text_remove_button.setGeometry(QtCore.QRect(390, 370, 31, 21))
        self.config_text_remove_button.setIcon(icon2)
        self.config_text_remove_button.setObjectName("config_text_remove_button")
        self.config_text_remove_button.setEnabled(False)
        
        self.config_text_add_button = QPushButton(self.config)
        self.config_text_add_button.setGeometry(QtCore.QRect(350, 370, 31, 21))
        self.config_text_add_button.setIcon(icon1)
        self.config_text_add_button.setObjectName("config_text_add_button")
        self.config_text_add_button.setEnabled(False)

    def setupStartButton(self):
        """Sets up the main buttons."""
        self.start_button = QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(690, 740, 191, 71))
        self.start_button.setObjectName("start_button")
        self.start_button.setEnabled(False)

    def setupLabels(self):
        """Sets up the additional labels."""
        self.uet = QLabel(self.centralwidget)
        self.uet.setGeometry(QtCore.QRect(30, 20, 81, 81))
        self.uet.setObjectName("uet")
        
        self.github = QLabel(self.centralwidget)
        self.github.setGeometry(QtCore.QRect(870, 10, 31, 31))
        self.github.setObjectName("github")
        self.github.setOpenExternalLinks(True)
        
        self.about = QLabel(self.centralwidget)
        self.about.setGeometry(QtCore.QRect(930, 10, 31, 31))
        self.about.setObjectName("about")
        
        self.guide = QLabel(self.centralwidget)
        self.guide.setGeometry(QtCore.QRect(900, 10, 21, 31))
        self.guide.setObjectName("guide")

    def retranslateUi(self):
        """Retranslates the UI elements."""
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("menu", "Phần mềm tạo slide tốt nghiệp"))
        self.title.setText(_translate("menu", "PHẦN MỀM TẠO SLIDE TỐT NGHIỆP"))
        self.template.setTitle(_translate("menu", "B1. Chọn mẫu"))
        self.template_broswe.setText(_translate("menu", "Duyệt"))
        self.template_label.setText(_translate("menu", "<html><head/><body><p><span style=\" font-weight:600;\">Chọn file Template </span>(.pptx)</p></body></html>"))
        self.dssv.setTitle(_translate("menu", "B2. Chọn danh sách sinh viên"))
        self.dssv_broswe.setText(_translate("menu", "Duyệt"))
        self.dssv_label.setText(_translate("menu", "<html><head/><body><p><span style=\" font-weight:600;\">Chọn danh sách sinh viên </span>(.csv)</p></body></html>"))
        self.save.setTitle(_translate("menu", "B4. Chọn vị trí lưu"))
        self.save_broswe.setText(_translate("menu", "Duyệt"))
        self.save_label.setText(_translate("menu", "<html><head/><body><p><span style=\" font-weight:600;\">Chọn vị trí lưu</span></p></body></html>"))
        self.start_button.setText(_translate("menu", "Bắt đầu"))
        self.uet.setText(_translate("menu", "<html><head/><body><p><img src=\":/main/uet\"/></p></body></html>"))
        self.uet.setToolTip("CTSV.UET.VNU")
        self.github.setText(_translate("menu", f'<html><head/><body><p><a href="{GITHUB_URL}"><img src=\":/main/github\"/></a></p></body></html>'))
        self.github.setToolTip("Github")
        self.config.setTitle(_translate("menu", "B3. Thiết lập thay thế"))
        item = self.config_image_table.horizontalHeaderItem(0)
        item.setText(_translate("menu", "Placeholder"))
        item = self.config_image_table.horizontalHeaderItem(1)
        item.setText(_translate("menu", "Tên ảnh mẫu"))
        self.config_text_label.setText(_translate("menu", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Text (Placeholder)</span></p></body></html>"))
        self.config_image_label.setText(_translate("menu", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Hình ảnh</span></p></body></html>"))
        self.config_image_autodownload_label.setText(_translate("menu", "Ảnh hỗ trợ tự động download nếu là liên kết"))
        __sortingEnabled = self.config_text_list.isSortingEnabled()
        self.config_text_list.setSortingEnabled(__sortingEnabled)
        self.about.setText(_translate("menu", "<html><head/><body><p><img src=\":/main/about\"/></p></body></html>"))
        self.about.setToolTip("About")
        self.guide.setText(_translate("menu", "<html><head/><body><p><img src=\":/main/guide\"/></p></body></html>"))
        self.guide.setToolTip("Hướng dẫn sử dụng")

    def handleUI(self):
        """Connects UI elements to their respective event handlers."""
        # Mỗi lần save_path, pptx_path, csv_path thay đổi, kiểm tra xem start_button có được enable không
        self.save_path.textChanged.connect(lambda: check_start_button(self))
        self.pptx_path.textChanged.connect(lambda: check_start_button(self))
        self.csv_path.textChanged.connect(lambda: check_start_button(self))

        # Xử lý sự kiện cho các button
        self.config_text_add_button.clicked.connect(lambda: config_text.add_item(self.config_text_list))
        self.config_text_remove_button.clicked.connect(lambda: config_text.remove_item(self.config_text_list))
        self.config_image_add_button.clicked.connect(lambda: config_images.add_item(self.config_image_table))
        self.config_image_remove_button.clicked.connect(lambda: config_images.remove_item(self.config_image_table))
        self.template_broswe.clicked.connect(lambda: menu_broswe_button.template_powerpoint_broswe(self.centralwidget, self.pptx_path))
        self.dssv_broswe.clicked.connect(lambda: menu_broswe_button.dssv_broswe(self.centralwidget, self.csv_path))
        self.save_broswe.clicked.connect(lambda: menu_broswe_button.save_path_broswe(self.centralwidget, self.save_path))
        self.start_button.clicked.connect(lambda: processing.Start())

        # Xử lý sự kiện cho input
        self.csv_path.textChanged.connect(lambda: load_csv.load_placeholders(self))
        self.pptx_path.textChanged.connect(lambda: load_pptx.load_shapes(self.pptx_path))

    def showProgress(self):
        """Shows the progress window."""
        if self.progress is None:
            self.progress = progress.Ui()
        self.progress.show()
